In [4]:
import tensorflow as tf
from tensorflow.keras.layers import Input ,Dense
from tensorflow.keras import Sequential
from tensorflow.keras.losses import MeanSquaredError, BinaryCrossentropy
from tensorflow.keras.activations import sigmoid
import logging

In [6]:
import numpy as np

In [44]:
X_train = np.array([[1.0, 2.0]], dtype=np.float32)           #(size in 1000 square feet)
Y_train = np.array([[300.0], [500.0]], dtype=np.float32)       #(price in 1000s of dollars)

In [45]:
X_train

array([[1., 2.]], dtype=float32)

In [46]:
linear_layer = tf.keras.layers.Dense(units=1, activation="linear") 

In [47]:
a1 = linear_layer(X_train)

In [48]:
a1

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[-2.9944658]], dtype=float32)>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('./deeplearning.mplstyle')
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from lab_utils_common import dlc
from lab_coffee_utils import load_coffee_data, plt_roast, plt_prob, plt_layer, plt_network, plt_output_unit
import logging
logging.getLogger("tensorflow").setLevel(logging.ERROR)
tf.autograph.set_verbosity(0)

In [51]:
X, Y = load_coffee_data()

print (X.shape, Y.shape)

(200, 2) (200, 1)


In [52]:
x_norm = tf.keras.layers.Normalization(axis=1)
x_norm.adapt(X)
Xn = x_norm(X)

In [54]:
Xt = np.tile(Xn,(1000,1))
Yt = np.tile(Y,(1000,1))

print(Xt.shape, Yt.shape)

(200000, 2) (200000, 1)


In [55]:
tf.random.set_seed(23534)
model = Sequential([
    tf.keras.Input(shape=(2,)),
    tf.keras.layers.Dense(3, activation="sigmoid", name="layer1"),
    tf.keras.layers.Dense(1, activation="sigmoid", name="layer2")
])

In [56]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 layer1 (Dense)              (None, 3)                 9         
                                                                 
 layer2 (Dense)              (None, 1)                 4         
                                                                 
Total params: 13 (52.00 Byte)
Trainable params: 13 (52.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [57]:
model.get_layer("layer1").get_weights()

[array([[ 1.07,  0.02, -0.72],
        [-0.97, -1.07, -0.38]], dtype=float32),
 array([0., 0., 0.], dtype=float32)]

In [58]:
model.compile(
    loss= tf.keras.losses.BinaryCrossentropy(),
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.01)
)

In [59]:
model.fit(Xt,Yt, epochs=10)

Epoch 1/10
6250/6250 [==============================] - 17s 3ms/step - loss: 0.1791
Epoch 2/10
6250/6250 [==============================] - 17s 3ms/step - loss: 0.1267
Epoch 3/10
6250/6250 [==============================] - 17s 3ms/step - loss: 0.1025
Epoch 4/10
6250/6250 [==============================] - 17s 3ms/step - loss: 0.0258
Epoch 5/10
6250/6250 [==============================] - 17s 3ms/step - loss: 0.0147
Epoch 6/10
6250/6250 [==============================] - 17s 3ms/step - loss: 0.0102
Epoch 7/10
6250/6250 [==============================] - 18s 3ms/step - loss: 0.0073
Epoch 8/10
6250/6250 [==============================] - 18s 3ms/step - loss: 0.0054
Epoch 9/10
6250/6250 [==============================] - 18s 3ms/step - loss: 0.0039
Epoch 10/10
6250/6250 [==============================] - 18s 3ms/step - loss: 0.0029


In [62]:
X,Y = load_coffee_data()

In [64]:
norm_1 = tf.keras.layers.Normalization(axis=1)
norm_1.adapt(X)
Xn = norm_1(X)

In [66]:
from tensorflow.keras.activations import sigmoid

In [68]:
g = sigmoid

In [71]:
def dense (a_in, W, b):
    
    units = W.shape[1]
    a_out = np.zeros_like(units)
    for j in range(units):
        w = W[:,i]
        z = np.matmul(w ,a_in) + b[j]
        a_out[j] = g(z)
    return a_out

In [ ]:
def sequential ():
    
    for i in range

In [1]:
import numpy as np

# Create a sample 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Iterate through all elements in a flattened manner
for element in array_2d.flat:
    print(element)


1
2
3
4
5
6
7
8
9
